name: giphy_get_demo
description: giphy_get Demo APP.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  # Easily configure any flutter application with global variables using a `.env` file.
  flutter_dotenv: ^5.2.1

  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  giphy_get:
    path: ../

  provider: ^6.1.5+1

dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - .env
